
export const OPENROUTER_MODELS = [
  { id: "anthropic/claude-haiku-4.5", name: "Anthropic/Claude Haiku-4.5" },
  { id: "anthropic/claude-opus-4.6", name: "Anthropic/Claude Opus-4.6" },
  { id: "anthropic/claude-opus-4.7", name: "Anthropic/Claude-Opus-4.7" },
  { id: "anthropic/claude-sonnet-4.5", name: "Anthropic/Claude-Sonnet-4.5" },
  { id: "anthropic/claude-sonnet-4.6", name: "Anthropic/Claude-Sonnet-4.6" },
  { id: "deepseek/deepseek-r1", name: "DeepSeek R1" },
  { id: "deepseek/deepseek-v4-flash", name: "DeepSeek V4 Flash" },
  { id: "deepseek/deepseek-v4-pro", name: "DeepSeek V4 Pro" },
  { id: "google/gemini-2.5-flash-lite", name: "Google/Gemini-2.5-Flash-Lite" },
  { id: "google/gemini-3-flash-preview", name: "Google/Gemini-3-Flash-Preview" },
  { id: "google/gemini-3.1-flash-lite-preview", name: "Google/Gemini-3.1-Flash-Lite-Preview" },
  { id: "google/gemini-3.1-pro-preview", name: "Google/Gemini-3.1-Pro-Preview" },
  { id: "google/gemma-4-31b-it", name: "Google/Gemma-4-31B-IT" },
  { id: "inicio/mercurio-2", name: "Início/Mercúrio-2" },
  { id: "meta-llama/llama-3.3-70b-instruct", name: "Meta Llama 3.3 70B" },
  { id: "minimax/minimax-m2.5", name: "Minimax/Minimax-M2.5" },
  { id: "mistralai/codestral-2508", name: "Mistralai/Codestral-2508" },
  { id: "mistralai/mistral-large", name: "Mistralai/Mistral-Large" },
  { id: "mistralai/mistral-medium-3.1", name: "Mistralai/Mistral-Medium-3.1" },
  { id: "mistralai/mistral-small-3.2-24b-instruct-2506", name: "Mistralai/Mistral-Small-3.2" },
  { id: "moonshotai/kimi-k2-pensamento", name: "Moonshotai/Kimi-K2-Pensamento" },
  { id: "openai/gpt-5", name: "OpenAI/GPT-5" },
  { id: "openai/gpt-5-mini", name: "OpenAI/GPT-5-mini" },
  { id: "openai/gpt-5-nano", name: "OpenAI/GPT-5-nano" },
  { id: "openai/gpt-5.1", name: "OpenAI/GPT-5.1" },
  { id: "openai/gpt-5.2", name: "OpenAI/GPT-5.2" },
  { id: "openai/gpt-5.2-pro", name: "OpenAI/GPT-5.2-pro" },
  { id: "openai/gpt-5.3-chat", name: "OpenAI/GPT-5.3-CHAT" },
  { id: "openai/gpt-5.4-mini", name: "OpenAI/GPT-5.4-mini" },
  { id: "openai/gpt-5.4-nano", name: "OpenAI/GPT-5.4-nano" },
  { id: "openai/gpt-5.4-pro", name: "OpenAI/GPT-5.4-pro" },
  { id: "openai/gpt-5.5", name: "OpenAI/GPT-5.5" },
  { id: "openai/gpt-oss-120b", name: "OpenAI/GPT-OSS-120B" },
  { id: "perplexity/sonar", name: "Perplexity/Sonar" },
  { id: "perplexity/sonar-pro", name: "Perplexity/Sonar-Pro" },
  { id: "qwen/qwen3-235b-a22b", name: "Qwen/QWEN3-235B-A22B" },
  { id: "qwen/qwen3.6-plus", name: "Qwen/QWEN3.6-plus" },
  { id: "x-ai/grok-4.3", name: "x-ai/Grok-4.3" },
  { id: "z-ai/glm-5", name: "Z-AI/GLM-5" }
];

export const DEFAULT_MODEL = "google/gemini-2.0-flash-001"; // Defaulting to a high-quality available model
